### ISSUE TITLE
blockageDensity_vector undefined in nemo_sim_mindistance 

### ISSUE THREAD

**Issue by ranimRR** [firyaguna/matlab-nemo-mmWave#1]
Hello,
I am a beginner in wireless communication and I am interested in understanding your project. I tried to run nemo_sim_mindistance script, however, blockageDensity_vector is not defined sim_parameters file so how I can define such parameter.

**Comment by ranimRR** [comment]
Is it possible for you to provide us the   sim_parameters file for sim_parameters file for nemo_sim_maxpower and nemo_sim_mindistance

**Comment by firyaguna** [comment]
Hi,

Could you try with the new code?

Cheers
